### ISSUE TITLE
Repository Adının Değiştirilmesi

### ISSUE THREAD

**Issue by mertssmnoglu** [cengizhan94/Java_BTK_Akademi#1]
Cengiz bey merhabalar 👋 , öncelikle Java ile ilgilenmiyor olsam da döküman anlamında güzel bir reponuz olduğunu söylemek isterim. 

Yalnız belirtmek isterim ki Java ile JavaScript farklı iki dildir. Reponuz, JavaScript ile ilgilenen birisi olarak projelerinize bakıp adında JavaScript gördüğüm için ilgimi çekmişti. Ancak kodlarda Java görünce hayal kırıklığına uğradımı belirtmek isterim. Genel olarak bir yanlış anlaşılmaya sokuyor maalesef, repo adını değiştirmenizi tavsiye eder iyi çalışmalar dilerim.

**Comment by cengizhan94** [comment]
Teşekkürler dostum yeni başladığımdan aradaki farkı bilmiyordum. şimdi sayende o farkı merak edip detaylıca araştırdım. sayende çok şey öğrendim. dikkatin için minnettarım.

**Comment by mertssmnoglu** [comment]
> Teşekkürler dostum yeni başladığımdan aradaki farkı bilmiyordum. şimdi sayende o farkı merak edip detaylıca araştırdım. sayende çok şey öğrendim. dikkatin için minnettarım.

Rica ederim, izlediğiniz yolda ve kariyerinizde başarılar diliyorum.
